### ISSUE TITLE
Move releases to GitHub

### ISSUE THREAD

**Issue by brianredbeard** [FOGProject/website#3]
Due to the tarnished reputation of Sourceforge as a "hotbed of malware" [1](http://www.information-age.com/industry/software/123459675/hotbed-malware-another-blow-sourceforge-google-discovers-588-pages-malicious-software), [2](http://sdtimes.com/sd-times-blog-sourceforge-now-a-source-of-malware/), [3](http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/) many users would be remiss in downloading software from the site.  Cutting a release and moving the binaries into GitHub (and updating the website) would be a wonderful step forward.

**Comment by mastacontrola** [comment]
I'm not aware of Sourceforge causing FOG to have malware.  First, the FOG Client would be the only thing I could think of as a potential hotbed for obtaining malware, of which we are strictly (now) on Github for anyway.

The installer of FOG is purely linux based, and I've never seen a download of FOG that has this embedded bit of software.  This might be because of us tarring the file for distribution, or it's not as simple for almost purely linux systems.  Maybe it's because it's been active for quite some time?

Our next release will be released to Github and sourceforge.  I will make some work to upload released FOG bits up to github as well as we do like to use Github now.  Our release after this current one (1.3.0 we're developing right now) will be completely on Github, and moved away from sourceforge altogether.
